<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated by Codia AI</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@600&display=swap" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@600&display=swap" />
    <style>
    :root {
        --default-font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
            Ubuntu, "Helvetica Neue", Helvetica, Arial, "PingFang SC",
            "Hiragino Sans GB", "Microsoft Yahei UI", "Microsoft Yahei",
            "Source Han Sans CN", sans-serif;
    }

    .main-container {
        overflow: hidden;
    }

    .main-container,
    .main-container * {
        box-sizing: border-box;
    }

    input,
    select,
    textarea,
    button {
        outline: 0;
    }
    </style>
</head>

<body>
    <div style="width:829px;height:1173.14px;background-color:#fbfbff;position:relative;overflow:hidden;margin:0 auto"
        class="main-container" id="casesheet">
        <div
            style="display:flex;width:36px;align-items:flex-start;flex-wrap:nowrap;position:relative;z-index:7;margin:175.57px 0 0 881px">
            <div
                style="display:flex;width:36px;padding:10px 10px 10px 10px;align-items:flex-start;flex-shrink:0;flex-wrap:nowrap;background-color:#ffffff;border-radius:8px;position:relative;z-index:8">
                <div style="width:16px;height:16px;flex-shrink:0;position:relative;z-index:9">
                    <div
                        style="width:16px;height:16px;background-position:center;background-image:url(https://static.codia.ai/image/2025-03-17/1e46a9f6-b892-45dd-8cdb-fceb53b70fe2.svg);background-size:cover;background-repeat:no-repeat;position:absolute;top:0;left:0;z-index:10">
                    </div>
                </div>
            </div>
        </div>
        <div style="position:absolute;top:10;bottom:0;left:0;right:0;z-index:55">
            <div style="width:829px;height:144px;position:relative;overflow:hidden;z-index:43;margin:0 0 0 0">
                <?php if (!empty($print_details['print_header'])) {
                $userdata = $this->session->userdata('hospitaladmin');
                $accessToken = $userdata['accessToken'] ?? '';

                $url = "https://phr-api.plenome.com/file_upload/getDocs";
                $client = curl_init($url);
                curl_setopt($client, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($client, CURLOPT_POST, true);
                curl_setopt($client, CURLOPT_POSTFIELDS, json_encode(['value' => $print_details['print_header']]));
                curl_setopt($client, CURLOPT_HTTPHEADER, [
                    'Content-Type: application/json',
                    'Authorization: ' . $accessToken
                ]);
                $response = curl_exec($client);
                curl_close($client);

                $logo_image = ($response !== false && strpos($response, '"NoSuchKey"') === false) ? "data:image/png;base64," . trim($response) : base_url() . "uploads/staff_images/no_image.png";
            ?>
                <div class="pprinta4">
                    <img src="<?= $logo_image ?>" class="img-responsive" style="height:100px; width: 100%;">
                </div>
                <?php } ?>
            </div>
            <div
                style="width:783.005px;height:2px;background-position:center;background-image:url(https://static.codia.ai/image/2025-03-17/df6c5fa2-e944-4be9-a9f5-4234b1edecaf.svg);background-size:cover;background-repeat:no-repeat;position:relative;z-index:54;margin:0.61px 0 0 23.001px">
            </div>
            <div
                style="width:787px;height:62px;background-color:#edeefd;border-radius:8px;position:relative;z-index:3;margin:12.961px 0 0 21px">
                <div
                    style="display:flex;width:187px;height:47px;gap:16px;align-items:center;flex-wrap:nowrap;position:absolute;top:50%;left:50%;transform:translate(-200.37%, -49.85%);z-index:4">
                    <div style="width:143px;height:47px;flex-shrink:0;position:relative;z-index:5">
                        <div
                            style="width:100%;height:100%;font-family:Poppins, var(--default-font-family);font-size:16px;font-weight:400;line-height:22px;position:absolute;top:0;left:0;text-align:left;z-index:6">
                            <span
                                style="font-size:12px;font-weight:500;line-height:22px;color:#4e54c8;position:relative;text-align:left">
                                Name
                            </span><br>
                            <span
                                style="font-size:16px;font-weight:600;line-height:24px;color:#1a1c42;position:relative;text-align:left">
                                <?=$result->patient_name?>
                            </span>
                        </div>
                    </div>
                </div>
                <div
                    style="display:flex;width:69.63%;height:66.67%;gap:16px;align-items:center;flex-wrap:nowrap;position:absolute;top:16.19%;left:28.06%;z-index:11">
                    <div
                        style="min-width:0;height:40px;flex-grow:1;flex-shrink:0;flex-basis:0;position:relative;z-index:12">
                        <div
                            style="width:100%;height:100%;font-size:12px;font-weight:500;line-height:18px;position:absolute;top:0;left:0;text-align:left;z-index:13">
                            <span
                                style="font-size:12px;font-weight:500;line-height:18px;color:#4e54c8;position:relative;text-align:left">
                                Patient ID
                            </span><br>
                            <span
                                style="font-size:14px;font-weight:600;line-height:21px;color:#1a1c42;position:relative;text-align:left">
                                PT<?= str_pad($result->patient_id, 4, '0', STR_PAD_LEFT) ?>
                            </span>
                        </div>
                    </div>
                    <div
                        style="width:1px;height:30px;flex-shrink:0;background-position:center;background-image:url('https://static.codia.ai/image/2025-03-17/50f91a9c-c2ab-4e11-8e5f-620cc2ddcf66.svg');background-size:cover;background-repeat:no-repeat;position:relative;z-index:14">
                    </div>
                    <div
                        style="min-width:0;height:40px;flex-grow:1;flex-shrink:0;flex-basis:0;position:relative;z-index:15">
                        <div
                            style="width:100%;height:100%;font-size:16px;font-weight:400;line-height:22px;position:absolute;top:0;left:0;text-align:left;z-index:16">
                            <span
                                style="font-size:12px;font-weight:500;line-height:22px;color:#4e54c8;position:relative;text-align:left">
                                Age & Gender<br>
                            </span>
                            <span
                                style="font-size:14px;font-weight:600;line-height:22px;color:#1a1c42;position:relative;text-align:left">
                                <?=$result->age?> Years, <?=$result->gender?>
                            </span>
                        </div>
                    </div>
                    <div
                        style="width:1px;height:30px;flex-shrink:0;background-position:center;background-image:url('https://static.codia.ai/image/2025-03-17/73c6e675-79a1-44d7-9929-3bd7b23a4888.svg');background-size:cover;background-repeat:no-repeat;position:relative;z-index:17">
                    </div>
                    <div
                        style="min-width:0;height:43px;flex-grow:1;flex-shrink:0;flex-basis:0;position:relative;z-index:18">
                        <div
                            style="width:100%;height:100%;font-size:16px;font-weight:400;line-height:22px;position:absolute;top:0;left:0;text-align:left;z-index:19">
                            <span
                                style="font-size:12px;font-weight:500;line-height:22px;color:#4e54c8;position:relative;text-align:left">
                                Mobile Number
                            </span><br>
                            <span
                                style="font-size:14px;font-weight:600;line-height:22px;color:#1a1c42;position:relative;text-align:left">
                                <?=$result->mobileno?>
                            </span>
                        </div>
                    </div>
                    <div
                        style="width:1px;height:30px;flex-shrink:0;background-position:center;background-image:url('https://static.codia.ai/image/2025-03-17/950cef02-eb33-446e-b316-e24cf212491b.svg');background-size:cover;background-repeat:no-repeat;position:relative;z-index:20">
                    </div>
                    <div style="width:129px;height:43px;flex-shrink:0;position:relative;z-index:21">
                        <div
                            style="width:100%;height:100%;font-size:16px;font-weight:400;line-height:22px;position:absolute;top:0;left:0;text-align:left;z-index:22">
                            <span
                                style="font-size:12px;font-weight:500;line-height:22px;color:#4e54c8;position:relative;text-align:left">
                                ABHA Address
                            </span><br>
                            <span
                                style="font-size:14px;font-weight:600;line-height:22px;color:#1a1c42;position:relative;text-align:left">
                                <?=$result->ABHA_number?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div
                style="width:787px;height:58px;background-color:#ffffff;position:relative;overflow:hidden;z-index:23;margin:0 0 0 21px">
                <div style="width:1196px;height:59px;position:relative;z-index:40;margin:9px 0 0 17px">
                    <div
                        style="display:flex;width:204px;height:40px;flex-direction:column;align-items:flex-start;flex-wrap:nowrap;position:absolute;top:0;left:423.586px;z-index:27">
                        <span
                            style="min-width:0;height:18px;align-self:stretch;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:400;line-height:18px;color:#666666;position:relative;text-align:left;white-space:nowrap;z-index:28">Doctor
                            Name</span><span
                            style="min-width:0;height:22px;align-self:stretch;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:14px;font-weight:600;line-height:22px;color:#333333;position:relative;text-align:left;white-space:nowrap;z-index:29">Dr.
                            <?=$result->name?>
                        </span>
                    </div>
                    <div
                        style="display:flex;width:131px;height:49.371px;flex-direction:column;gap:2px;align-items:center;position:absolute;top:1px;left:634px;z-index:40">
                        <!-- Barcode Image -->
                        <svg id="barcode" style="width: 125px; height: 30px;"></svg>

                        <!-- Patient ID Below Barcode -->
                        <span
                            style="font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;text-align:center;white-space:nowrap;z-index:42">
                            PT<?= str_pad($result->patient_id, 4, '0', STR_PAD_LEFT) ?>
                        </span>
                    </div>
                    <div
                        style="display:flex;width:404px;height:40px;flex-direction:column;align-items:flex-start;flex-wrap:nowrap;position:absolute;top:1.43px;left:0;z-index:24">
                        <span
                            style="min-width:0;height:18px;align-self:stretch;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:400;line-height:18px;color:#666666;position:relative;text-align:left;white-space:nowrap;z-index:25">Address</span><span
                            style="min-width:0;height:22px;align-self:stretch;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:14px;font-weight:600;line-height:22px;color:#333333;position:relative;text-align:left;white-space:nowrap;z-index:26"><?=$result->address?></span>
                    </div>
                    <div
                        style="display:flex;width:204px;height:40px;flex-direction:column;align-items:flex-start;flex-wrap:nowrap;position:absolute;top:7px;left:813.5px;z-index:30">
                        <span
                            style="min-width:0;height:18px;align-self:stretch;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:400;line-height:18px;color:#666666;position:relative;text-align:left;white-space:nowrap;z-index:31">Duration
                            Count</span><span
                            style="min-width:0;height:22px;align-self:stretch;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:14px;font-weight:600;line-height:22px;color:#333333;position:relative;text-align:left;white-space:nowrap;z-index:32">1
                            Day</span>
                    </div>
                    <div
                        style="display:flex;width:36px;height:36px;align-items:flex-start;flex-wrap:nowrap;position:absolute;top:23px;left:1160px;z-index:33">
                        <div
                            style="display:flex;width:36px;padding:10px 10px 10px 10px;align-items:flex-start;flex-shrink:0;flex-wrap:nowrap;background-color:#ffffff;border-radius:8px;border:1.5px solid #6b70d1;position:relative;z-index:34">
                            <div style="width:16px;height:16px;flex-shrink:0;position:relative;z-index:35">
                                <div
                                    style="width:16px;height:16px;background-position:center;background-image:url(https://static.codia.ai/image/2025-03-17/ed23eebc-9f58-4683-b06f-ca38dfcdbb52.svg);background-size:cover;background-repeat:no-repeat;position:absolute;top:0;left:0;z-index:36">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    style="display:flex;width:222px;flex-direction:column;align-items:flex-start;flex-wrap:nowrap;position:relative;z-index:37;margin:3px 0 0 830px">
                    <span
                        style="min-width:0;height:18px;align-self:stretch;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:400;line-height:18px;color:#666666;position:relative;text-align:left;white-space:nowrap;z-index:38">Status</span><span
                        style="display:flex;width:384.58px;height:22px;justify-content:flex-start;align-items:flex-start;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:14px;font-weight:600;line-height:22px;color:#22c55e;position:relative;text-align:left;white-space:nowrap;z-index:39">Approved</span>
                </div>
            </div>
            <div style="width:829px;height:48px;position:relative;overflow:hidden;margin:845.569px 0 0 0">
                <span
                    style="display:flex;height:18px;justify-content:flex-start;align-items:center;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#8f98b3;position:absolute;top:calc(50% - 9px);left:calc(50% - 97.5px);text-align:left;white-space:nowrap;z-index:1">Design
                    & Developed by Plenome</span>
            </div>
            <div
                style="display:flex;width:787px;height:812px;flex-direction:column;gap:16px;align-items:flex-start;flex-wrap:nowrap;position:absolute;top:295.141px;left:24px;overflow:hidden;z-index:55">
                <div
                    style="display:flex;min-width:0;flex-direction:column;gap:8px;align-items:flex-start;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;position:relative;z-index:56">
                    <span
                        style="height:21px;align-self:stretch;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:14px;font-weight:600;line-height:21px;color:#01030f;position:relative;text-align:left;white-space:nowrap;z-index:57">Vitals</span>
                    <div
                        style="display:flex;flex-direction:column;gap:8px;align-items:flex-start;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;position:relative;z-index:58">
                        <div
                            style="display:flex;align-items:center;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;border-radius:4px;position:relative;overflow:hidden;z-index:59">
                            <div
                                style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:60">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:61">Temperature
                                </span>
                            </div>
                            <div
                                style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:62">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:63">Pulse</span>
                            </div>
                            <div
                                style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:64">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:65">Blood
                                    Pressure
                                </span>
                            </div>
                            <div
                                style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:66">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:67">Respiratory
                                    Rate</span>
                            </div>
                            <div
                                style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:68">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:69">Weight</span>
                            </div>
                            <div
                                style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:70">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:71">Height</span>
                            </div>
                            <div
                                style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:72">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:73">Sp02</span>
                            </div>
                        </div>
                        <div
                            style="display:flex;align-items:center;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;border-radius:8px;position:relative;overflow:hidden;z-index:74">
                            <div
                                style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:75">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:76"><?=$vitals['temperature']?>
                                    C</span>
                            </div>
                            <div
                                style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:77">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:78"><?=$vitals['pulse']?>
                                    bpm</span>
                            </div>
                            <div
                                style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:79">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:80"><?=$vitals['bp']?>
                                    mmhg</span>
                            </div>
                            <div
                                style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:81">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:82"><?=$vitals['respiration']?>
                                    rpm</span>
                            </div>
                            <div
                                style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:83">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:84"><?=$vitals['weight']?>
                                    kg</span>
                            </div>
                            <div
                                style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:85">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:86"><?=$vitals['height']?>
                                    cm</span>
                            </div>
                            <div
                                style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:87">
                                <span
                                    style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:88"><?=$vitals['spo2']?>
                                    C</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    style="display: flex; flex-direction: column; gap: 8px; align-items: flex-start; align-self: stretch; flex-shrink: 0; position: relative; z-index: 89;">
                    <span
                        style="display: flex; width: 122px; height: 21px; justify-content: center; align-items: center; flex-shrink: 0; font-family: Poppins, var(--default-font-family); font-size: 14px; font-weight: 600; line-height: 21px; color: #01030f; position: relative; text-align: center; white-space: nowrap; z-index: 90;">
                        Chief Complaints
                    </span>

                    <table style="width: 100%; border-collapse: collapse; position: relative; z-index: 91;">
                        <thead>
                            <tr style="background-color: #b8bfff;">
                                <th
                                    style="padding: 8px 4px; font-family: Poppins, var(--default-font-family); font-size: 12px; font-weight: 500; line-height: 18px; color: #01030f; text-align: center;">
                                    Symptoms</th>
                                <th
                                    style="padding: 8px 4px; font-family: Poppins, var(--default-font-family); font-size: 12px; font-weight: 500; line-height: 18px; color: #01030f; text-align: center;">
                                    Body Site</th>
                                <th
                                    style="padding: 8px 4px; font-family: Poppins, var(--default-font-family); font-size: 12px; font-weight: 500; line-height: 18px; color: #01030f; text-align: center;">
                                    Duration</th>
                                <th
                                    style="padding: 8px 4px; font-family: Poppins, var(--default-font-family); font-size: 12px; font-weight: 500; line-height: 18px; color: #01030f; text-align: center;">
                                    Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($clinical_notes['chiefComplaintsBasic'] as $data): ?>
                            <tr style="background-color: rgba(255, 255, 255, 0);">
                                <td
                                    style="padding: 8px 4px; font-family: Poppins, var(--default-font-family); font-size: 12px; font-weight: 500; line-height: 18px; color: #01030f; text-align: center;">
                                    <?=$data['complaints_name']?>
                                </td>
                                <td
                                    style="padding: 8px 4px; font-family: Poppins, var(--default-font-family); font-size: 12px; font-weight: 500; line-height: 18px; color: #01030f; text-align: center;">
                                    -
                                </td>
                                <td
                                    style="padding: 8px 4px; font-family: Poppins, var(--default-font-family); font-size: 12px; font-weight: 500; line-height: 18px; color: #01030f; text-align: center;">
                                    <?=$clinical_notes['chiefComplaintDetails']['count']?> Days
                                </td>
                                <td
                                    style="padding: 8px 4px; font-family: Poppins, var(--default-font-family); font-size: 12px; font-weight: 500; line-height: 18px; color: #01030f; text-align: center;">
                                    <?=$clinical_notes['chiefComplaintDetails']['remarks']?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <div style="display:flex;width:781px;flex-direction:column;gap:10px;align-items:flex-start;flex-wrap:nowrap;position:relative;margin:0 auto"
                        class="main-container">
                        <div
                            style="display:flex;width:138px;align-items:flex-start;flex-shrink:0;flex-wrap:nowrap;position:relative">
                            <span
                                style="height:18px;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:left;white-space:nowrap;z-index:1">Past
                                Treatment History</span>
                        </div>
                        <div style="width:765px;height:100%;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:400;line-height:18px;color:#01030f;position:relative;margin:0 auto"
                            class="main-container">
                            <?=$clinical_notes['pastTreatmentHistory']['history']?>
                        </div>
                    </div>
                    <div
                        style="display:flex;min-width:0;flex-direction:column;gap:8px;align-items:flex-start;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;position:relative;z-index:56">
                        <span
                            style="height:21px;align-self:stretch;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:14px;font-weight:600;line-height:21px;color:#01030f;position:relative;text-align:left;white-space:nowrap;z-index:57">Diagnosis</span>
                        <div
                            style="display:flex;flex-direction:column;gap:8px;align-items:flex-start;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;position:relative;z-index:58">
                            <div
                                style="display:flex;align-items:center;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;border-radius:4px;position:relative;overflow:hidden;z-index:59">
                                <div
                                    style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:60">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:61">Test
                                        Categories
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:62">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:63">Sub
                                        categories </span>
                                </div>
                                <div
                                    style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:64">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:65">Laboratory
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:66">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:67">Remarks</span>
                                </div>
                            </div>
                            <?php if (!empty($clinical_notes['diagnosisReport'])): ?>
                            <?php foreach ($clinical_notes['diagnosisReport'] as $report): ?>
                            <div
                                style="display:flex;align-items:center;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;border-radius:8px;position:relative;overflow:hidden;z-index:74">
                                <div
                                    style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:75">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:76">
                                        <?= $report['test_categories'] ?>
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:77">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:78">
                                        <?= $report['sub_category'] ?>
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:79">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:80">
                                        <?= $report['laboratory'] ?>
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:81">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:82">
                                        <?= $report['remarks'] ?>
                                    </span>
                                </div>
                            </div>
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div style="display:flex;width:781px;flex-direction:column;gap:10px;align-items:flex-start;flex-wrap:nowrap;position:relative;margin:0 auto"
                        class="main-container">
                        <div
                            style="display:flex;width:138px;align-items:flex-start;flex-shrink:0;flex-wrap:nowrap;position:relative">
                            <span
                                style="height:18px;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:left;white-space:nowrap;z-index:1">Treatment
                                Advice</span>
                        </div>
                        <div style="width:765px;height:100%;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:400;line-height:18px;color:#01030f;position:relative;margin:0 auto"
                            class="main-container">
                            <?=$clinical_notes['treatmentAdvice']['treatment_advice']?>
                        </div>
                    </div>
                    <div
                        style="display:flex;min-width:0;flex-direction:column;gap:8px;align-items:flex-start;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;position:relative;z-index:56">
                        <div
                            style="display:flex;flex-direction:column;gap:8px;align-items:flex-start;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;position:relative;z-index:58">
                            <div
                                style="display:flex;align-items:center;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;border-radius:4px;position:relative;overflow:hidden;z-index:59">
                                <div
                                    style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:60">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:61">Medicine
                                        Name
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:62">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:63">Dosage
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:64">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:65">Frequency
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:66">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:67">Timing</span>
                                </div>
                                <div
                                    style="display:flex;height:32px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:#b8bfff;position:relative;z-index:66">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:67">Quantity</span>
                                </div>
                            </div>
                            <?php if (!empty($prescription)): ?>
                            <?php foreach ($prescription as $prescription): ?>
                            <div
                                style="display:flex;align-items:center;align-self:stretch;flex-shrink:0;flex-wrap:nowrap;border-radius:8px;position:relative;overflow:hidden;z-index:74">
                                <div
                                    style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:75">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:76">
                                        <?= $prescription['medicine_name'] ?>
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:77">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:78">
                                        <?= $prescription['medicine_name'] ?>
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:79">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:80">
                                        <?= $prescription['dosage'] ?>
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:81">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:82">
                                        <?= $prescription['frequency'] ?>
                                    </span>
                                </div>
                                <div
                                    style="display:flex;height:34px;padding:8px 4px 8px 4px;gap:4px;justify-content:center;align-items:center;flex-grow:1;flex-shrink:0;flex-basis:0;flex-wrap:nowrap;background-color:rgba(255, 255, 255, 0);position:relative;z-index:81">
                                    <span
                                        style="height:18px;flex-grow:1;flex-shrink:0;flex-basis:auto;font-family:Poppins, var(--default-font-family);font-size:12px;font-weight:500;line-height:18px;color:#01030f;position:relative;text-align:center;white-space:nowrap;z-index:82">
                                        <?= $prescription['duration_count'] ?>
                                    </span>
                                </div>
                            </div>
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsbarcode/3.11.0/JsBarcode.all.min.js"></script>
<script>
function download() {
    const {
        jsPDF
    } = window.jspdf;
    let doc = new jsPDF("p", "mm", "a4");
    let casesheet = document.getElementById("casesheet");

    html2canvas(casesheet, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
    }).then(canvas => {
        let imgData = canvas.toDataURL("image/png");
        let imgWidth = 210,
            pageHeight = 297,
            imgHeight = (canvas.height * imgWidth) / canvas.width,
            y = 0;

        while (y < imgHeight) {
            doc.addImage(imgData, "PNG", 0, -y, imgWidth, imgHeight);
            y += pageHeight;
            if (y < imgHeight) doc.addPage();
        }

        doc.save("CaseSheet.pdf");
    });
}
download();
</script>
<script>
document.addEventListener("DOMContentLoaded", function() {
    let patientID = "PT<?= str_pad($result->patient_id, 4, '0', STR_PAD_LEFT) ?>";
    JsBarcode("#barcode", patientID, {
        format: "CODE128",
        displayValue: false,
        lineColor: "#000",
        width: 2,
        height: 40
    });
});
</script>


</html>