name: PHP HMS CI/CD Deployment

on:
  push:
    branches:
      - localDev
      - cloudDev
      - test
      - uat
      - demo
      - prod

jobs:
  deploy:
    runs-on: [ self-hosted, php-hms-localDev-runner ]
    # runs-on: ubuntu-latest
    
    steps:
    
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set environment-specific deployment configurations
      - name: Set environment variables
        id: set_vars
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/localDev" ]]; then
            export DEPLOYMENT_TARGET="local"
            echo "Deploying to local server"
          elif [[ "$GITHUB_REF" == "refs/heads/cloudDev" ]]; then
            export DEPLOYMENT_TARGET="cloud"
            export GROUP_NAME="cloudDev-group"
            echo "Deploying to AWS (DEV environment)"
          elif [[ "$GITHUB_REF" == "refs/heads/test" ]]; then
            export DEPLOYMENT_TARGET="cloud"
            export GROUP_NAME="test-group"
            echo "Deploying to AWS (Test environment)"
          elif [[ "$GITHUB_REF" == "refs/heads/uat" ]]; then
            export DEPLOYMENT_TARGET="cloud"
            export GROUP_NAME="uat-group"
            echo "Deploying to AWS (UAT environment)"
          else
            echo "No matching environment for branch $GITHUB_REF"
            exit 1
          fi

          echo "target=$DEPLOYMENT_TARGET" >> $GITHUB_ENV
          echo "group=$GROUP_NAME" >> $GITHUB_ENV

      # Step 3: Deploy to Local Server (only for local-dev branch)
      - name: Deploy to Local Server
        if: env.target == 'local'  
        run: |
          sudo cp -r $GITHUB_WORKSPACE/* /var/www/php-hms-frontend/
          echo $PWD
          sudo cp ~/env/.env.php /var/www/php-hms-frontend/.env


      # Step 4: Deploy to AWS CodeDeploy 
      - name: Configure AWS Credentials
        if: env.target == 'cloud'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Create CodeDeploy Deployment
        if: env.target == 'cloud'  
        run: |
          echo "Deploying to AWS CodeDeploy (Application: PHP-HMS, Group: ${{ env.group }})"
          aws deploy create-deployment \
            --application-name PHP-demo \
            --deployment-group-name ${{ env.group }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
          echo "AWS CodeDeploy deployment complete."
